blank_issues_enabled: false
contact_links:
  - name: Dúvidas?
    url:  https://twitter.com/intent/tweet?text=%40devMozao%20Moz%C3%A3o%20t%C3%B4%20com%20uma%20d%C3%BAvida%20aqui%20...
    about: Mande um Tweet pedindo socorro pra mim!